[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.42.0", features = ["full"] }
sea-orm = { version = "1.1.2", features = ["sqlx-mysql", "runtime-tokio", "macros"]}
